-- Puzzlox standalone schema (no pixi_ prefixes)
-- Run this in a fresh Supabase project.

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  role TEXT NULL DEFAULT 'user'::text,
  completed_puzzles INTEGER NULL DEFAULT 0,
  placed_pieces INTEGER NULL DEFAULT 0,
  created_at TIMESTAMPTZ NULL DEFAULT timezone('utc'::text, now()),
  total_play_time INTEGER NULL DEFAULT 0,
  last_active_at TIMESTAMPTZ NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_username_key UNIQUE (username)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.rooms (
  id SERIAL NOT NULL,
  creator_name TEXT NOT NULL,
  image_url TEXT NOT NULL,
  piece_count INTEGER NOT NULL,
  max_players INTEGER NOT NULL,
  password TEXT NULL,
  status TEXT NULL DEFAULT 'active'::text,
  created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ NULL,
  difficulty TEXT NULL DEFAULT 'medium'::text,
  has_password BOOLEAN NULL DEFAULT false,
  total_play_time_seconds INTEGER NULL DEFAULT 0,
  is_private BOOLEAN NULL DEFAULT false,
  room_code UUID NULL DEFAULT extensions.uuid_generate_v4(),
  created_by BIGINT NULL,
  CONSTRAINT rooms_pkey PRIMARY KEY (id),
  CONSTRAINT rooms_difficulty_check CHECK (
    difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text, 'nightmare'::text])
  ),
  CONSTRAINT rooms_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_rooms_created_by
  ON public.rooms USING btree (created_by) TABLESPACE pg_default
  WHERE (created_by IS NOT NULL);

CREATE TABLE IF NOT EXISTS public.pieces (
  room_id BIGINT NOT NULL,
  piece_index INTEGER NOT NULL,
  x DOUBLE PRECISION NULL,
  y DOUBLE PRECISION NULL,
  is_locked BOOLEAN NULL DEFAULT false,
  snapped_by TEXT NULL,
  rotation_quarter SMALLINT NULL DEFAULT 0,
  is_back_face BOOLEAN NULL DEFAULT false,
  CONSTRAINT pieces_pkey PRIMARY KEY (room_id, piece_index),
  CONSTRAINT pieces_rotation_quarter_check CHECK (
    rotation_quarter = ANY (ARRAY[0, 1, 2, 3])
  ),
  CONSTRAINT pieces_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.scores (
  room_id BIGINT NOT NULL,
  username TEXT NOT NULL,
  score INTEGER NULL DEFAULT 0,
  CONSTRAINT scores_pkey PRIMARY KEY (room_id, username),
  CONSTRAINT scores_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.user_identities (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  provider TEXT NOT NULL,
  provider_user_id TEXT NOT NULL,
  password_hash TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login_at TIMESTAMPTZ NULL,
  CONSTRAINT user_identities_pkey PRIMARY KEY (id),
  CONSTRAINT user_identities_provider_provider_user_id_key UNIQUE (provider, provider_user_id),
  CONSTRAINT user_identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT user_identities_provider_check CHECK (
    provider = ANY (ARRAY['web_local'::text, 'toss'::text])
  )
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_user_identities_user_id
  ON public.user_identities USING btree (user_id) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.user_room_visits (
  user_id BIGINT NOT NULL,
  room_id INTEGER NOT NULL,
  last_visited_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_room_visits_pkey PRIMARY KEY (user_id, room_id),
  CONSTRAINT user_room_visits_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
  CONSTRAINT user_room_visits_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_user_room_visits_user_time
  ON public.user_room_visits USING btree (user_id, last_visited_at DESC) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.puzzles (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  piece_id INTEGER NOT NULL,
  current_x DOUBLE PRECISION NOT NULL,
  current_y DOUBLE PRECISION NOT NULL,
  is_locked BOOLEAN NULL DEFAULT false,
  locked_by TEXT NULL,
  CONSTRAINT puzzles_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;
